!!python/unicode auto_launch_webapp: null
!!python/unicode data_collection:
  !!python/unicode recording_period:
    !!python/unicode end_msg: !!python/unicode RECORDING_STOPPED
    !!python/unicode event_period: {!!python/unicode end_msg: !!python/unicode END_EVENT_PERIOD,
      !!python/unicode start_msg: !!python/unicode START_EVENT_PERIOD}
    !!python/unicode start_msg: !!python/unicode RECORDING_STARTED
  !!python/unicode video_event_sync:
    !!python/unicode colors: [255, 0]
    !!python/unicode cycle_count: 15
    !!python/unicode phase_duration: 0.125
    !!python/unicode region: [0, 0, 20, 20]
!!python/unicode event_buffer_length: 1048
!!python/unicode event_loop_rate: 0.005
!!python/unicode experiment_inactive_token: null
!!python/unicode experimenter_server: {!!python/unicode address: !!python/unicode 127.0.0.1,
  !!python/unicode port: 8888}
!!python/unicode ioHub:
  !!python/unicode config: !!python/unicode ..\last_iohub_config_no_eyetracker.yaml
  !!python/unicode process_affinity: []
!!python/unicode manual_termination:
  !!python/unicode keyboard: {!!python/unicode key: !!python/unicode q, !!python/unicode modifier: !!python/unicode CONTROL_LEFT}
!!python/unicode noise_calculation: {!!python/unicode win_size: 0.2}
!!python/unicode process_affinity: []
!!python/unicode remaining_processes_affinity: []
!!python/unicode results_root_folder: !!python/unicode .\results
!!python/unicode screen_capture:
  !!python/unicode dshow_filters:
    !!python/unicode audio: !!python/unicode virtual-audio-capturer
    !!python/unicode ffmpeg_settings: {!!python/unicode rtbufsize: 1404000}
    !!python/unicode video: !!python/unicode screen-capture-recorder
  !!python/unicode ffmpeg: {!!python/unicode exe: !!python/unicode ffmpeg.exe, !!python/unicode path: !!python/unicode ..\..\..\bin\ffmpeg\bin,
    !!python/unicode stderr_file: !!python/unicode ffmpeg_stderr, !!python/unicode stdout_file: !!python/unicode ffmpeg_stdout}
  !!python/unicode http_stream:
    !!python/unicode ffmpeg_settings:
      !!python/unicode b: {!!python/unicode v: 1600}
      !!python/unicode r: 30
      !!python/unicode scale: 1.0
      !!python/unicode threads: 0
    !!python/unicode host: !!python/unicode 127.0.0.1
    !!python/unicode read_port: 8084
    !!python/unicode uri: !!python/unicode screenstream
    !!python/unicode write_port: 8082
  !!python/unicode media_file:
    !!python/unicode extension: !!python/unicode mkv
    !!python/unicode ffmpeg_settings: {!!python/unicode codec: !!python/unicode libx264,
      !!python/unicode crf: 0, !!python/unicode g: 250, !!python/unicode pix_fmt: !!python/unicode yuv420p,
      !!python/unicode preset: !!python/unicode ultrafast, !!python/unicode threads: 0}
    !!python/unicode name: !!python/unicode screen_capture
  !!python/unicode screen_index: 0
  !!python/unicode screen_resolution: [1920, 1080]
session_defaults: {code: !!python/unicode s3}
!!python/unicode web_application:
  !!python/unicode notifications:
    !!python/unicode eyetracker:
      !!python/unicode proportion_valid_samples:
        !!python/unicode error:
          !!python/unicode color: null
          !!python/unicode flashrate: 0.25
          !!python/unicode growl: {!!python/unicode duration: !!python/unicode MANUAL,
            !!python/unicode fillcolor: null, !!python/unicode text: !!python/unicode Sample
              Data Loss Above 80%. Check participant positioning, !!python/unicode textcolor: null}
          !!python/unicode threshold: 0.8
        !!python/unicode warning:
          !!python/unicode color: null
          !!python/unicode flashrate: null
          !!python/unicode growl: {!!python/unicode duration: 3.0, !!python/unicode fillcolor: null,
            !!python/unicode text: !!python/unicode Sample Data Loss Above 10%., !!python/unicode textcolor: null}
          !!python/unicode threshold: 0.1
