# iohub_config.yaml: settings related to the iohub process and the device types that are to be enabled for the
# experiment.
monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 0
        physical_dimensions:
            width: 500
            height: 281
            unit_type: mm
        default_eye_distance:
            surface_center: 500
            unit_type: mm
        psychopy_monitor_name: default
    - Keyboard:
        name: keyboard
        save_events: True
        stream_events: True
        auto_report_events: False
    - Mouse:
        name: mouse
        save_events: True
        stream_events: True
        auto_report_events: False
    - Experiment:
        name: experiment
        save_events: True
        stream_events: True     
data_store:
    filename: iohub_events
    enable: True
