# iohub_config.yaml: settings related to the iohub process and the device types that are to be enabled for the
# experiment.
monitor_devices:
    - Display:
        name: display
        reporting_unit_type: pix
        device_number: 0
        physical_dimensions:
            width: 500
            height: 281
            unit_type: mm
        default_eye_distance:
            surface_center: 500
            unit_type: mm
        psychopy_monitor_name: default
    - Keyboard:
        name: keyboard
        save_events: True
        stream_events: True
        auto_report_events: False
    - Mouse:
        name: mouse
        save_events: True
        stream_events: True
        auto_report_events: False
    - Experiment:
        name: experiment
        save_events: True
        stream_events: True
    - eyetracker.hw.tobii.EyeTracker:
        enable: True
        name: tracker
        auto_report_events: False
        model_name:
        serial_number:
        monitor_event_types: [ MonocularEyeSampleEvent, BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent, SaccadeStartEvent, SaccadeEndEvent, BlinkStartEvent, BlinkEndEvent]
        runtime_settings:
            track_eyes: BINOCULAR_AVERAGED
            sampling_rate: 60
        calibration:
            type: FIVE_POINTS
            randomize: True
            auto_pace: True
            pacing_speed: 1.0
            screen_background_color: [128,128,128]            
            target_type: CIRCLE_TARGET
            target_attributes:
                 outer_diameter: 35
                 outer_stroke_width: 2
                 outer_fill_color: [128,128,128]
                 outer_line_color: [255,255,255]
                 inner_diameter: 7
                 inner_stroke_width: 1
                 inner_color: [0,0,0]
                 inner_fill_color: [0,0,0]
                 inner_line_color: [0,0,0]
                 animate:
                     enable: True
                     movement_velocity: 900.0  # 500 pix / sec
                     expansion_ratio: 3.0  # expands to 3 x the starting size
                     expansion_speed: 60.0  # exapands at 30.0 pix / sec
                     contract_only: True        
data_store:
    filename: iohub_events
    enable: True
