!!python/unicode event_buffer_length: 1048
!!python/unicode event_filters:
  !!python/unicode tracker:
    !!python/unicode class_name: !!python/unicode EyeTrackerEventParser
    !!python/unicode file_path: !!python/unicode ..\lib\event_filters\eyetracker.py
    !!python/unicode params:
      !!python/unicode adaptive_vel_thresh_history: 5.0
      !!python/unicode position_filter: {!!python/unicode knot_pos: !!python/unicode center,
        !!python/unicode length: 3, !!python/unicode name: !!python/unicode MovingWindowFilter}
      !!python/unicode velocity_filter: {!!python/unicode knot_pos: !!python/unicode center,
        !!python/unicode length: 3, !!python/unicode name: !!python/unicode MedianFilter}
    !!python/unicode stream_filtered_only: true
!!python/unicode event_loop_rate: 0.005
!!python/unicode experiment_inactive_token: null
!!python/unicode ioHub:
  !!python/unicode config: !!python/unicode ..\settings\last_iohub_config_smi.yaml
  !!python/unicode process_affinity: []
!!python/unicode manual_termination:
  !!python/unicode keyboard: {!!python/unicode key: !!python/unicode q, !!python/unicode modifier: !!python/unicode CONTROL_LEFT}
!!python/unicode process_affinity: []
!!python/unicode recording_period:
  !!python/unicode end_msg: !!python/unicode RECORDING_STOPPED
  !!python/unicode event_period: {!!python/unicode end_msg: !!python/unicode END_EVENT_PERIOD,
    !!python/unicode start_msg: !!python/unicode START_EVENT_PERIOD}
  !!python/unicode start_msg: !!python/unicode RECORDING_STARTED
!!python/unicode remaining_processes_affinity: []
!!python/unicode results_root_folder: !!python/unicode ..\Results
!!python/unicode screen_capture:
  !!python/unicode dshow_filters:
    !!python/unicode audio: !!python/unicode virtual-audio-capturer
    !!python/unicode ffmpeg_settings: {!!python/unicode rtbufsize: 1404000}
    !!python/unicode video: !!python/unicode screen-capture-recorder
  !!python/unicode ffmpeg: {!!python/unicode exe: !!python/unicode ffmpeg.exe, !!python/unicode path: !!python/unicode ..\bin\ffmpeg\bin,
    !!python/unicode stderr_file: !!python/unicode ffmpeg_stderr, !!python/unicode stdout_file: !!python/unicode ffmpeg_stdout}
  !!python/unicode http_stream:
    !!python/unicode ffmpeg_settings:
      !!python/unicode b: {!!python/unicode v: 1600}
      !!python/unicode r: 30
      !!python/unicode scale: 1.0
      !!python/unicode threads: 0
    !!python/unicode read_port: 8084
    !!python/unicode uri: !!python/unicode screenstream
    !!python/unicode write_port: 8082
  !!python/unicode media_file:
    !!python/unicode extension: !!python/unicode mkv
    !!python/unicode ffmpeg_settings: {!!python/unicode codec: !!python/unicode libx264,
      !!python/unicode crf: 0, !!python/unicode g: 250, !!python/unicode pix_fmt: !!python/unicode yuv420p,
      !!python/unicode preset: !!python/unicode ultrafast, !!python/unicode threads: 0}
    !!python/unicode name: !!python/unicode screen_capture
  !!python/unicode screen_index: 0
  !!python/unicode screen_resolution: [1920, 1080]
session_defaults: {code: !!python/unicode s4}
!!python/unicode video_event_sync:
  !!python/unicode colors: [255, 0]
  !!python/unicode cycle_count: 15
  !!python/unicode phase_duration: 0.125
  !!python/unicode region: [0, 0, 20, 20]
!!python/unicode view_server: {!!python/unicode address: 192.168.1.11, !!python/unicode port: 8888}
