!!python/unicode data_store: {!!python/unicode enable: true, !!python/unicode filename: !!python/unicode ..\Results\Default_Experiment\iohub_events}
!!python/unicode monitor_devices:
- !!python/unicode Display:
    !!python/unicode default_eye_distance: {!!python/unicode surface_center: 500,
      !!python/unicode unit_type: !!python/unicode mm}
    !!python/unicode device_number: 0
    !!python/unicode name: !!python/unicode display
    !!python/unicode physical_dimensions: {!!python/unicode height: 281, !!python/unicode unit_type: !!python/unicode mm,
      !!python/unicode width: 500}
    !!python/unicode psychopy_monitor_name: !!python/unicode default
    !!python/unicode reporting_unit_type: !!python/unicode pix
- !!python/unicode Keyboard: {!!python/unicode auto_report_events: false, !!python/unicode name: !!python/unicode keyboard,
    !!python/unicode save_events: true, !!python/unicode stream_events: true}
- !!python/unicode Mouse: {!!python/unicode auto_report_events: false, !!python/unicode name: !!python/unicode mouse,
    !!python/unicode save_events: true, !!python/unicode stream_events: true}
- !!python/unicode Experiment: {!!python/unicode name: !!python/unicode experiment,
    !!python/unicode save_events: true, !!python/unicode stream_events: true}
- !!python/unicode eyetracker.hw.smi.iviewx.EyeTracker:
    !!python/unicode calibration:
      !!python/unicode auto_pace: true
      !!python/unicode pacing_speed: !!python/unicode FAST
      !!python/unicode screen_background_color: 20
      !!python/unicode show_validation_accuracy_window: false
      !!python/unicode target_attributes: {!!python/unicode target_color: 239, !!python/unicode target_inner_color: !!python/unicode RED,
        !!python/unicode target_size: 30}
      !!python/unicode target_type: !!python/unicode CIRCLE_TARGET
      !!python/unicode type: !!python/unicode FIVE_POINTS
    !!python/unicode event_buffer_length: 1024
    !!python/unicode model_name: !!python/unicode REDm
    !!python/unicode monitor_event_types: [!!python/unicode MonocularEyeSampleEvent,
      !!python/unicode BinocularEyeSampleEvent, !!python/unicode FixationStartEvent,
      !!python/unicode FixationEndEvent, !!python/unicode SaccadeStartEvent, !!python/unicode SaccadeEndEvent,
      !!python/unicode BlinkStartEvent, !!python/unicode BlinkEndEvent]
    !!python/unicode name: !!python/unicode tracker
    !!python/unicode network_settings: {!!python/unicode receive_ip_address: !!python/unicode 127.0.0.1,
      !!python/unicode receive_port: 5555, !!python/unicode send_ip_address: !!python/unicode 127.0.0.1,
      !!python/unicode send_port: 4444}
    !!python/unicode runtime_settings:
      !!python/unicode sample_filtering: {!!python/unicode FILTER_ALL: !!python/unicode FILTER_OFF}
      !!python/unicode sampling_rate: 60
      !!python/unicode track_eyes: !!python/unicode BINOCULAR_AVERAGED
      !!python/unicode vog_settings: {!!python/unicode pupil_measure_types: !!python/unicode PUPIL_DIAMETER}
    !!python/unicode save_events: true
    !!python/unicode stream_events: true
