###############################################################################
#
# PLEASE READ:
# Four settings in this file MUST BE UPDATED when the software is first being
# setup for a given computer / screen resolution. The following config settings
# must be modified for the software to function correctly:
#
# 1. ioHub -> config : Relative path of the iohub config file, including the
#   file name. Path must be relative to the application run.py script location.
#
# 2. screen_capture->screen_resolution : Resolution of the *data collection*
#   app. display that screen capture video will be coming from.
#
# 3. screen_capture -> http_stream -> host : The ip address of the web server 
#    application PC.
#
# 4. screen_capture -> experimenter_server -> address : The ip address of the 
#    web server application PC.
#
###############################################################################
  
# ioHub client side settings

event_buffer_length: 1048

process_affinity: []
remaining_processes_affinity: []

ioHub:
    process_affinity: []
    config: ..\iohub_config_no_eyetracker.yaml

################# ETS Screen Streaming Application Specific ###################

results_root_folder: .\results
experiment_inactive_token:

auto_launch_webapp:

screen_capture:
    screen_index: 0
    screen_resolution: [1920,1080]

    ffmpeg:
        path: '..\..\..\bin\ffmpegwin32\bin\'
        exe: ffmpeg.exe
        stdout_file: ffmpeg_stdout
        stderr_file: ffmpeg_stderr
        
    dshow_filters:
        # Screen captue frames are taken by using Screen Capture Recorder
        #   software. The installer in in the dependancies folder of the
        #   project. This filter MUST be installed and configured or User
        #   Monitor will not work.
        #
        video: screen-capture-recorder
        # audio options: 
        #   leave blank: no audio saved to screen cap video
        #   virtual-audio-capturer: save sound from computer audio out.
        #   [ NOT WORKING ] Microphone: save what comes in the default audio input selected
        #       by / within the OS settings.     
        audio: virtual-audio-capturer
        ffmpeg_settings:
            #  real time buffer size (in K)
            rtbufsize: 1404000 # 2097152 K
            
    # params related to saving the screen stream to file
    media_file:
        name: screen_capture
        extension: mkv
        ffmpeg_settings:
            codec: libx264
            pix_fmt: yuv420p
            crf: 18.0
            preset: veryfast
            g: 250
            threads: 0
            
    #params related to the realtime stream to the experimenter app. 
    #
    http_stream:
        host: 192.168.1.37
        write_port: 8082
        read_port: 8084
        uri: screenstream
        ffmpeg_settings:
            scale: 0.5
            threads: 0
            # frame rate
            r: 30
            # bitrates (in K)
            b:
                # video
                v: 1600
            
################# ETS Experimenter Control & Monitoring Server #################

experimenter_server:
    address: 192.168.1.37
    port: 8888
    
    #streaming iohub events to experiment app server
    event_streaming:
        rest_uri: events
        filter: []
        stream_interval: 0.05

manual_termination:
    keyboard:
        key: c
        modifier: CONTROL_LEFT
        
event_loop_rate: 0.005