!!python/unicode auto_launch_webapp: null
!!python/unicode code: !!python/unicode logs
!!python/unicode description: !!python/unicode Test of using ioHub for gathering all
  the data we need.
!!python/unicode display_experiment_dialog: false
!!python/unicode display_session_dialog: false
!!python/unicode event_buffer_length: 1048
!!python/unicode event_loop_rate: 0.005
!!python/unicode experiment_inactive_token: null
!!python/unicode experimenter_server:
  !!python/unicode address: !!python/unicode 192.168.1.10
  !!python/unicode event_streaming:
    !!python/unicode filter: []
    !!python/unicode rest_uri: !!python/unicode events
    !!python/unicode stream_interval: 0.05
  !!python/unicode port: 8888
!!python/unicode ioHub:
  !!python/unicode config: !!python/unicode ..\iohub_config.yaml
  !!python/unicode process_affinity: []
!!python/unicode manual_termination:
  !!python/unicode keyboard: {!!python/unicode key: !!python/unicode c, !!python/unicode modifier: !!python/unicode CONTROL_LEFT}
!!python/unicode process_affinity: []
!!python/unicode remaining_processes_affinity: []
!!python/unicode results_root_folder: !!python/unicode .\results
!!python/unicode screen_capture:
  !!python/unicode dshow_filters:
    !!python/unicode audio: !!python/unicode virtual-audio-capturer
    !!python/unicode ffmpeg_settings: {!!python/unicode rtbufsize: 1404000}
    !!python/unicode video: !!python/unicode screen-capture-recorder
  !!python/unicode ffmpeg: {!!python/unicode exe: !!python/unicode ffmpeg.exe, !!python/unicode path: !!python/unicode ..\..\..\bin\ffmpegwin32\bin\,
    !!python/unicode stderr_file: !!python/unicode ffmpeg_stderr, !!python/unicode stdout_file: !!python/unicode ffmpeg_stdout}
  !!python/unicode http_stream:
    !!python/unicode ffmpeg_settings:
      !!python/unicode b: {!!python/unicode v: 1600}
      !!python/unicode r: 30
      !!python/unicode scale: 0.5
      !!python/unicode threads: 0
    !!python/unicode host: !!python/unicode 192.168.1.10
    !!python/unicode read_port: 8084
    !!python/unicode uri: !!python/unicode screenstream
    !!python/unicode write_port: 8082
  !!python/unicode media_file:
    !!python/unicode extension: !!python/unicode mkv
    !!python/unicode ffmpeg_settings: {!!python/unicode codec: !!python/unicode libx264,
      !!python/unicode crf: 18.0, !!python/unicode g: 250, !!python/unicode pix_fmt: !!python/unicode yuv420p,
      !!python/unicode preset: !!python/unicode veryfast, !!python/unicode threads: 0}
    !!python/unicode name: !!python/unicode screen_capture
  !!python/unicode screen_index: 0
  !!python/unicode screen_resolution: [1280, 1024]
!!python/unicode session_defaults: {!!python/unicode code: !!python/unicode s3, !!python/unicode comments: !!python/unicode None,
  !!python/unicode name: !!python/unicode Session Name}
!!python/unicode session_variable_order: [!!python/unicode name, !!python/unicode code,
  !!python/unicode comments]
!!python/unicode title: !!python/unicode Eyetracking
!!python/unicode version: !!python/unicode 0.1
